version: 0.2

phases:
  install:
    commands:
      - echo Installing dependencies and listing repo content
      - ls -lah
  pre_build:
    commands:
      - echo Validating templates
      - aws cloudformation validate-template --template-body file://route53.yaml
      - aws cloudformation validate-template --template-body file://certificates.yaml      
  build:
    commands:
      - echo Build stage
      - bash ci-build.sh
  post_build:
    commands:
      - echo List artifacts
      - bash ci-post-build.sh
