AWSTemplateFormatVersion: '2010-09-09'
Description: Route53 DNS Zone Setup

Parameters:
  ProjectName:
    Description: Name for the current project
    Type: String
  ModuleName:
    Description: Stage name
    Type: String    
  StageName:
    Description: Stage name
    Type: String

Conditions:
  ProdStage: !Equals [!Ref StageName, 'prod']
  OtherStage: !Not [!Equals [!Ref StageName, 'prod']]

Resources:
  DomainCustomResource:
    Type: "Custom::SmDomain"
    Properties:
      ServiceToken: 
        Fn::ImportValue:
          !Sub "${ProjectName}-SMR-lambda-SmrArn"
      secretname: !Ref ProjectName
      secretvalue: 'route53-domain-name'   

  Route53HostedZone:
    Type: AWS::Route53::HostedZone
    DeletionPolicy: Retain
    Properties:
      Name: !If
        - ProdStage
        - !GetAtt DomainCustomResource.Response
        - !Sub
          - ${StageName}.${Domain}
          - { Domain: !GetAtt DomainCustomResource.Response }
      HostedZoneConfig:
        Comment: !Sub "Domain zone for stage ${StageName}"

Outputs:
  HostedZone:
    Description: A reference to the HostedZone
    Condition: ProdStage
    Value: !Ref Route53HostedZone
    Export:
      Name: aws-dns-HostedZone
  DevHostedZone:
    Description: A reference to the HostedZone
    Condition: OtherStage    
    Value: !Ref Route53HostedZone
    Export:
      Name: !Sub aws-${StageName}-dns-HostedZone